name: Lint GitHub Actions workflows

on: workflow_call

jobs:
  actionlint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up actionlint
        id: setup_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Lint
        run: ${{ steps.setup_actionlint.outputs.executable }} -color
