name: Publish npm package function-kysely-tailordb

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: packages/kysely-tailordb/package.json
          registry-url: https://registry.npmjs.org

      - name: Update npm and corepack
        run: |
          npm i -g npm@latest
          npm i -g corepack@latest

      - name: Publish
        working-directory: packages/kysely-tailordb
        run: |
          corepack enable
          pnpm install
          pnpm run build
          pnpm publish --no-git-checks --access public
