name: Publish npm package function-kysely-tailordb

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: packages/kysely-tailordb/package.json
          registry-url: https://registry.npmjs.org

      - name: Update corepack
        run: |
          npm i -g corepack@latest

      - name: Publish
        working-directory: packages/kysely-tailordb
        run: |
          corepack enable
          pnpm install
          pnpm run build
          pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
