name: Test packages/types

on: workflow_call

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: ./package.json
          registry-url: https://registry.npmjs.org

      - name: Setup pnpm
        run: |
          npm i -g corepack@latest
          corepack enable

      - name: Install deps
        working-directory: packages/types
        run: |
          pnpm install

      - name: Test
        working-directory: packages/types
        run: |
          pnpm run test
